### ISSUE TITLE
Upload des fichiers de justificatif

### ISSUE THREAD

**Issue by jeantil** [publicissapient-france/xndf#14]
En tant qu'utilisateur, je veux pouvoir uploader un fichier de justificatif pour l'associer à une ligne de dépense.

**Comment by cyrille-leclerc** [comment]
Veux tu un bucket amazon-s3 pour stocker les justificatifs ?

**Comment by jeantil** [comment]
Euh pourquoi pas  ? je pensais les mettre dans un mongodb mais n'importe quel stockage de masse peut faire l'affaire. 

Au passage, si on a accès à des bases mongo hébergées ça m'interesse très fort.

**Comment by cyrille-leclerc** [comment]
> stockage de masse

Quel besoin de fiabilité ? 
La volumétrie de scans de factures risque de devenir importante si on veut les conserver (pour le moment, Nadia et Sara impriment tout)

> Mongo hébergé

Seulement sur Amazon (vérifier la latence)
Les prix seraient https://mongohq.com/pricing
Une base 2Go serait j'imagine mutualisable étant donné nos volumétries. Si c'est du non-mutualisable, 20$/Month est un peu cher

**Comment by jeantil** [comment]
> Quel besoin de fiabilité ?   

Pas de besoin de fiabilité énorme pour le moment: l'idée c'est déjà d'avoir une appli dans laquelle on peut préparer ses notes de frais et qui les envoie automatiquement par mail à Nadia et Sara.

Du coup, même en cas de perte de données ou de coupure de service il reste toujours l'option d'envoyer le mail à la mimine ou de refaire la note de frais.

A terme si ça interesse le bureau on pourra regarder à quel coût fiabiliser la bête ...

> Une base 2Go

Je viens de regarder mes justificatifs : le plus gros fait 400ko. On peut stocker ~5000 justificatif dans 2Go (avant compression) pour 50 personnes, ça fait 100 justificatifs par personne, 2 justifs par mois => 50 mois de stockage si j'ai bien compté, ça laisse de la marge.

C'est de la grosse louche, il y a des gens qui font beaucoup plus de notes de frais, d'autres moins, les justifs peuvent être bien plus petits ( par mois j'ai 750ko et pas 1Mo), on peut mettre de la compression, ....
