### ISSUE TITLE
Afficher les justificatifs d'une ligne de dépense

### ISSUE THREAD

**Issue by jeantil** [publicissapient-france/xndf#15]
En tant qu'utilisateur, je veux pouvoir consulter les fichiers de justificatif associés a une ligne de dépense.

**Comment by pgayvallet** [comment]
So what? is it done already?

**Comment by jeantil** [comment]
Nope but it will never be and I needed to reduce clutter in my GH interface
:)

Le mer. 25 nov. 2020 à 23:25, Pierre Gayvallet <notifications@github.com> a
écrit :
