### ISSUE TITLE
Add gas, meal & misc ndf type

### ISSUE THREAD

**Issue by jeanlaurent** [publicissapient-france/xndf#25]
Actually we got

Lodging - Phone - Internet - Transportation

I suggest you add :

Gas - Meal - Misceanelous

**Comment by jeantil** [comment]
Do you have a suggestion for a better handling of this reference list than what is done at the moment ? 
https://github.com/jeantil/xndf/blob/develop/public/tpl/expense-detail.html

**Comment by jeanlaurent** [comment]
1. Hard code it. This won't change much. I don't know your server code, but it may have impact there. It's a bit simplistic.
2. Write the list in a property-like file/ hard-code it in a scala collection equivalent, write a resource that provide the list as json with a very high TTL, make a backbone view-control-it. It's simple but a bit more complex.
3. Create a table in a relational database, then write a repository to read it, then... Too javaesque. I'll stop there.

Btw, I did try to write my lastest ndf with your tool, I need Meal & Misc at least this month, and used Gas by the past. So it _must_ be added somehow.

**Comment by jeantil** [comment]
For now, the expense types are defined as individual types in domain.scala I guess I would need to use reflexion to build the list of known types and send it client side. For the moment I simply hard coded the list.

```
  @Salat
  sealed trait Expense {
    val amount: Double
    val qualifier: String
  }

  case class Lodging(amount: Double) extends Expense {
    val qualifier = "Lodging"
  }

  case class Transportation(amount: Double) extends Expense {
    val qualifier = "Transportation"
  }

  case class Gas(amount: Double) extends Expense {
    val qualifier = "Gas"
  }

  case class Meal(amount: Double) extends Expense {
    val qualifier = "Meal"
  }

  case class Phone(amount: Double) extends Expense {
    val qualifier = "Phone"
  }

  case class Internet(amount: Double) extends Expense {
    val qualifier = "Internet"
  }

  case class Other(amount: Double) extends Expense {
    val qualifier = "Other"
  }
```
