### ISSUE TITLE
Champ description illisible

### ISSUE THREAD

**Issue by fsarradin** [publicissapient-france/xndf#29]
Je clique sur "New expense". Lorsque je saisis le champ "Description", le mot "Description" ne disparaît pas.

Le bug ne se reproduit pas lorsque je saisis une autre ligne juste après.

Testé sous Google Chrome Version 21.0.1180.82

**Comment by jeantil** [comment]
j'ai fait quelques tests : il semble qu'il y ait un problème avec la gestion du focus de webkit. je vais virer le placeholder pour l'instant

**Comment by jeantil** [comment]
Finalement le place holder n'a pas l'air d'être critique du coup je vais fermer le bug

quand on reverra l'UI et l'ergonomie je referai une passe
