### ISSUE TITLE
Email non envoyé ?

### ISSUE THREAD

**Issue by ebriand** [publicissapient-france/xndf#44]
J'ai rempli une note de frais avec 3 éléments et lorsque j'ai cliqué sur l'envoi, je n'ai rien reçu. Par contre en renvoyant l'email à partir de la homepage pour la même note de frais ça a fonctionné.

Peut être un problème de branchement d'action quelque part ? 

Jean vient de m'envoyer l'email suivant d'ailleurs : 

"On vient de faire des tests. Il semble que cliquer sur send direct ne marche pas il faut faire save au moins une fois avant..."

**Comment by jeantil** [comment]
Le fix est déployé sur Heroku.

Enjoy
