### ISSUE TITLE
Bug : Manque une ligne de note dans Excel

### ISSUE THREAD

**Issue by eservent** [publicissapient-france/xndf#45]
Salut, 
Deja merci pour l'appli, ca va vraiment faire gagner un peu de temps...
Pour le moment, j'ai un bug sur ma feuille Excel, il manque la deuxieme ligne qui parle du Phone.

Pourtant mes deux images sont bien envoyées.

Voilà,
Si tu veux plus d'infos : 06 64 32 94 74

**Comment by jeantil** [comment]
ça fera surtout gagner du temps si ça marche :) j'ai réussi a reproduire le problème je vais voir si je peux corriger ça ce soir ...

**Comment by jeantil** [comment]
Je ne peux pas relivrer en journée, ça montera ce soir. 

Merci pour le bug report !

**Comment by jeantil** [comment]
C'est relivré 

Enjoy !
