### ISSUE TITLE
Utiliser Google Apps comme unique IDentity Provider OpenID

### ISSUE THREAD

**Issue by cyrille-leclerc** [publicissapient-france/xndf#8]
Maintenant que tout @xebia.fr a un compte Google Apps, peut-on utiliser Google Apps comme unique IDP OpenID et ne plus se connecter à Crowd ?

**Comment by jeantil** [comment]
Pour l'instant, Xndf n'utilise pas Crowd et laisse le choix du provider. A terme, oui il faudra utiliser l'openid googleapps mais j'avais commencé a regarder pour le faire et je n'avais pas tout compris, ça semble assez compliqué. 
En gros je pense qu'il faut qu'on créé un endpoint xebiafr, qu'on y place un fichier avec un format précis pour qu'il délègue l'identification au endpoint google pour le domaine xebiafr

Il faudra se refaire une soirée pour faire le test

**Comment by cyrille-leclerc** [comment]
On mettra Julien Buret dans la boucle, il m'a dit avoir testé avec succès une intégration avec l'authentification Google.

**Comment by jeantil** [comment]
L'intégration avec google ne pose pas de problème mais n'importe qui avec
un compte google peut se connecter

On peut vérifier dans les applis que le compte mail est bien @xebia.fr mais
c pas super propre

## 

jean
Le 12 mai 2012 17:48, "Cyrille Le Clerc" <
reply@reply.github.com>
a écrit :

**Comment by cyrille-leclerc** [comment]
Vérifier @xebia.fr dans le code me semble acceptable :-)
